meta_product_name: "Outrek"
meta_title: "Outrek | Group Safety Adventure Planner"
meta_description: "Organize your next trip outdoors with Outrek's collaborative packing list"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@outrek_app"   # required for Twitter Cards
